### PR TITLE
Add PHP 8.4 support

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by heiglandreas** [comment]
😂 I was just considering whether I raise exactly this PR. Great to see that I am not the only one getting things ready for PHP8.4 😁

**Comment by lcobucci** [comment]
@Slamdunk thanks!

**Comment by bpolaszek** [comment]
Hi @lcobucci, would you mind tagging a new release? 🙃

**Comment by lcobucci** [comment]
> Hi @lcobucci, would you mind tagging a new release? 🙃 

@bpolaszek this is already in https://github.com/lcobucci/clock/releases/tag/3.3.0 (which isn't the latest release).

**Pull request merged**
